SELECT 
    EMP.CODEMP AS CODIGO_EMPRESA,
    EMP.RAZAOSOCIAL AS RAZAO_SOCIAL,
    EMP.NOMEFANTASIA AS NOME_FANTASIA,
    EMP.CGC AS CNPJ_CPF,
    EMP.INSCESTAD AS INSCRICAO_ESTADUAL,
    EMP.INSCMUN AS INSCRICAO_MUNICIPAL,
    
    -- Contatos e Web
    EMP.EMAIL,
    EMP.HOMEPAGE AS SITE,
    EMP.TELEFONE,
    
    -- Endereço Completo
    ENDER.TIPO AS TIPO_LOGRADOURO,
    ENDER.NOMEEND AS LOGRADOURO,
    EMP.NUMEND AS NUMERO,
    EMP.COMPLEMENTO,
    BAI.NOMEBAI AS BAIRRO,
    CID.NOMECID AS CIDADE,
    CID.UF AS CODIGO_UF, -- (Referência para a tabela TSIUFS)
    EMP.CEP,
    
    -- Informações Fiscais e Tributárias da Empresa
    EMP.SIMPLES AS OPTANTE_SIMPLES,
    EMP.SIMPLESNACNAUF AS CONVENIO_SIMPLES_UF,
    EMP.CODREGTRIB AS CODIGO_REGIME_TRIBUTARIO,
    EMP.CLASSTRIB AS CLASSIFICACAO_TRIBUTARIA,
    EMP.INDOPCCP AS TRIB_CONTRIB_PREVIDENCIARIA,
    EMP.INFOOBRA AS CONTRIBUICAO_PATRONAL,
    EMP.LIVROSFISCAIS AS GERA_LIVROS_FISCAIS,

    -- Campos para aba Fiscal do Odoo
    EMP.CNAEPREPON AS CNAE_PREPONDERANTE,
    EMP.NATJUR AS NATUREZA_JURIDICA

FROM TSIEMP EMP
LEFT JOIN TSIEND ENDER ON EMP.CODEND = ENDER.CODEND
LEFT JOIN TSIBAI BAI   ON EMP.CODBAI = BAI.CODBAI
LEFT JOIN TSICID CID   ON EMP.CODCID = CID.CODCID

WHERE EMP.CODEMP = 1
