SELECT CODEMP, CODLOCAL, CODPROD, ESTOQUE, RESERVADO 
FROM TGFEST
WHERE ESTOQUE > 0
  AND TGFEST.CODPROD IN (
SELECT PRO.CODPROD FROM TGFPRO PRO 
  WHERE PRO.ATIVO = 'S'
  AND substr(PRO.CODPROD, 1, 2) = '20'
  AND substr(PRO.CODPROD, 6, 1) = '1'

  )
