SELECT
  PAR.CODPARC,
  PAR.NOMEPARC,
  PAR.RAZAOSOCIAL,
  PAR.CGC_CPF,
  PAR.IDENTINSCESTAD,
  PAR.TIPPESSOA,
  PAR.ATIVO,
  PAR.CLIENTE,
  PAR.FORNECEDOR,
  PAR.EMAIL,
  PAR.TELEFONE,
  PAR.FAX,
  PAR.CEP,
  PAR.NUMEND,
  PAR.COMPLEMENTO,
  ENDR.NOMEEND,
  BAI.NOMEBAI,
  CID.NOMECID,
  UFS.UF AS UF_SIGLA,
  UFS.DESCRICAO AS UF_NOME,
  PAI.ABREVIATURA AS PAIS_SIGLA,
  PAI.DESCRICAO AS PAIS_NOME
FROM TGFPAR PAR
LEFT JOIN TSIEND ENDR ON ENDR.CODEND = PAR.CODEND
LEFT JOIN TSIBAI BAI ON BAI.CODBAI = PAR.CODBAI
LEFT JOIN TSICID CID ON CID.CODCID = PAR.CODCID
LEFT JOIN TSIUFS UFS ON UFS.CODUF = CID.UF
LEFT JOIN TSIPAI PAI ON PAI.CODPAIS = UFS.CODPAIS
WHERE PAR.ATIVO = 'S'
