WITH PROD_BASE AS (
  SELECT
    PRO.CODPROD,
    PRO.DESCRPROD,
    PRO.REFFORN,
    PRO.PESOBRUTO,
    PRO.CODVOL,
    PRO.USOPROD,
    PRO.NCM,
    PRO.TEMISS,
    PRO.MARCA,
    PRO.CODLOCALPADRAO,
    PRO.CODESPECST,
    PRO.ORIGPROD,
    PRO.TIPOITEMSPED
  FROM TGFPRO PRO
  WHERE PRO.ATIVO = 'S'
    AND substr(PRO.CODPROD, 1, 2) = '20'
    AND substr(PRO.CODPROD, 6, 1) IN ('1', '2', '3')
),
PEM AS (
  SELECT
    PEM.CODPROD,
    MAX(PEM.CODESPECST) AS CODESPECST,
    MAX(PEM.ORIGPROD) AS ORIGPROD,
    MAX(PEM.TIPOITEMSPED) AS TIPOITEMSPED,
    MAX(PEM.USOPROD) AS USOPROD
  FROM TGFPEM PEM
  WHERE PEM.CODPROD IN (SELECT CODPROD FROM PROD_BASE)
  GROUP BY PEM.CODPROD
),
TOP_REF AS (
  SELECT
    T.CODTIPOPER,
    T.DESCROPER,
    T.CUPOMFISCAL,
    T.TIPMOV,
    ROW_NUMBER() OVER (
      PARTITION BY T.CODTIPOPER
      ORDER BY T.DHALTER DESC
    ) AS RN
  FROM TGFTOP T
),
TOP_ATUAL AS (
  SELECT
    CODTIPOPER,
    DESCROPER,
    CUPOMFISCAL,
    TIPMOV
  FROM TOP_REF
  WHERE RN = 1
),
HIST AS (
  SELECT
    ITE.CODPROD,
    CAB.TIPMOV,
    CAB.CODTIPOPER,
    CAB.DTNEG,
    CAB.NUNOTA,
    ROW_NUMBER() OVER (
      PARTITION BY ITE.CODPROD, CAB.TIPMOV
      ORDER BY CAB.DTNEG DESC, CAB.NUNOTA DESC
    ) AS RN
  FROM TGFITE ITE
  JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
  WHERE ITE.CODPROD IN (SELECT CODPROD FROM PROD_BASE)
    AND CAB.CODTIPOPER IS NOT NULL
    AND CAB.TIPMOV IN ('V', 'C')
),
TOP_SALES AS (
  SELECT
    H.CODPROD,
    H.CODTIPOPER AS CODTIPOPER_SALES,
    TA.DESCROPER AS DESCROPER_SALES
  FROM HIST H
  LEFT JOIN TOP_ATUAL TA ON TA.CODTIPOPER = H.CODTIPOPER
  WHERE H.TIPMOV = 'V'
    AND TA.TIPMOV = 'V'
    AND H.RN = 1
),
TOP_PURCHASES AS (
  SELECT
    CODPROD,
    CODTIPOPER AS CODTIPOPER_PURCHASES,
    DESCROPER AS DESCROPER_PURCHASES
  FROM (
    SELECT
      H.CODPROD,
      H.CODTIPOPER,
      TA.DESCROPER,
      ROW_NUMBER() OVER (
        PARTITION BY H.CODPROD
        ORDER BY
          CASE WHEN H.TIPMOV = 'C' THEN 0 ELSE 1 END,
      H.DTNEG DESC,
      H.NUNOTA DESC
      ) AS RN
    FROM HIST H
    LEFT JOIN TOP_ATUAL TA ON TA.CODTIPOPER = H.CODTIPOPER
    WHERE H.TIPMOV = 'C'
      AND TA.TIPMOV = 'C'
  ) Q
  WHERE Q.RN = 1
),
TOP_POS AS (
  SELECT
    CODPROD,
    CODTIPOPER AS CODTIPOPER_POS,
    DESCROPER AS DESCROPER_POS
  FROM (
    SELECT
      H.CODPROD,
      H.CODTIPOPER,
      TA.DESCROPER,
      ROW_NUMBER() OVER (
        PARTITION BY H.CODPROD
        ORDER BY H.DTNEG DESC, H.NUNOTA DESC
      ) AS RN
    FROM HIST H
    JOIN TOP_ATUAL TA ON TA.CODTIPOPER = H.CODTIPOPER
    WHERE H.TIPMOV = 'V'
      AND TA.TIPMOV = 'V'
      AND NVL(TA.CUPOMFISCAL, 'N') = 'S'
  ) Q
  WHERE Q.RN = 1
)
SELECT
  PRO.CODPROD,
  PRO.DESCRPROD,
  PRO.REFFORN,
  PRO.PESOBRUTO,
  PRO.CODVOL,
  PRO.USOPROD,
  COALESCE(PEM.USOPROD, PRO.USOPROD) AS USOPROD_FISCAL,
  PRO.NCM,
  NCM.UNITRIBUTACAO,
  COALESCE(PEM.CODESPECST, PRO.CODESPECST) AS CODESPECST,
  COALESCE(PEM.ORIGPROD, PRO.ORIGPROD) AS ORIGPROD,
  COALESCE(PEM.TIPOITEMSPED, PRO.TIPOITEMSPED) AS TIPOITEMSPED,
  PRO.TEMISS,
  PRO.MARCA,
  PRO.CODLOCALPADRAO,
  TS.CODTIPOPER_SALES,
  TS.DESCROPER_SALES,
  TP.CODTIPOPER_PURCHASES,
  TP.DESCROPER_PURCHASES,
  TX.CODTIPOPER_POS,
  TX.DESCROPER_POS
FROM PROD_BASE PRO
LEFT JOIN PEM ON PEM.CODPROD = PRO.CODPROD
LEFT JOIN TGFNCM NCM ON NCM.CODNCM = PRO.NCM
LEFT JOIN TOP_SALES TS ON TS.CODPROD = PRO.CODPROD
LEFT JOIN TOP_PURCHASES TP ON TP.CODPROD = PRO.CODPROD
LEFT JOIN TOP_POS TX ON TX.CODPROD = PRO.CODPROD
