SELECT
  VEN.CODVEND,
  VEN.APELIDO,
  VEN.EMAIL AS EMAIL_VENDEDOR,
  VEN.ATIVO AS ATIVO_VENDEDOR,
  VEN.TIPVEND,
  VEN.CODPARC,
  PAR.NOMEPARC,
  PAR.RAZAOSOCIAL,
  PAR.EMAIL AS EMAIL_PARCEIRO,
  PAR.CGC_CPF,
  PAR.VENDEDOR,
  PAR.ATIVO AS ATIVO_PARCEIRO
FROM TGFVEN VEN
LEFT JOIN TGFPAR PAR ON PAR.CODPARC = VEN.CODPARC
WHERE VEN.ATIVO = 'S'
